### ISSUE TITLE
cannot access BSseq object

### ISSUE THREAD

**Issue by hernandezvargash** [Lauren-Blake/Reg_Evo_Primates#1]
Thanks for this great resource!
After downloading the full BSseq object ("allData") from GEO I'm getting this error when I try to access it in R: _no slot of name "rowRanges" for this object of class "BSseq"_. I get the same error when trying to update the object with `updateObject(allData)`
I'd appreciate any hint to what the problem may be or if you can point me to another BSseq object with human data only.
Thanks a lot,
Hector

**Comment by Lauren-Blake** [comment]
Hi Hector- Apologies for the delay, I have graduated and currently work in industry. 

I believe that what you're describing is due to a version issue. 

Julien used bsseq version 0.10 at the time. He has also provided the following code in R using Bioconductor version 3.12; R 4.0.3; bsseq 1.26.0:

library(bsseq)
load("GSE112356_combined.RDa")
str(allData) # doesn't work
allData <- updateObject(allData) # doesn't work either, maybe the version I used is really too old?
getObjectSlots(allData) 

This is more interesting, and lists the insides of the object. We cannot access the slots with the usual accessors (they expect the update class format), but we can still do it the old-school way:

allData@rowData # a GRanges object showing the 46594397 sites
allData@colData # a DataFrame object showing the 48 samples
head(allData@assays$data$M) # a 46594397 X 48 matrix of number of methylated reads 
head(allData@assays$data$Cov) # a 46594397 X 48 matrix of read coverage 

Maybe the easiest at that point is to rebuild a clean bsseq object from these slots... Another option (I haven't tried) is to downgrade bsseq to version 0.10 and save the methylation/coverage slots as matrices or sparse matrices.

Please let me know if you are still having issues.

**Comment by Lauren-Blake** [comment]
P.S. Not sure if you have seen this, but once you have gotten the methylation data processed, the website https://lauren-blake.github.io/Regulatory_Evol/analysis/ contains some downstream analyses that I did for the paper. Hopefully that code/analyses are helpful.

**Comment by hernandezvargash** [comment]
Hi Lauren, I followed your recommendation and built a new BSseq object with:
```
BSnew <- BSseq(M=allData@assays$data$M,
               Cov=allData@assays$data$Cov,
               pData = allData@colData,
               gr=allData@rowData,
               sampleNames = rownames(allData@colData))
```
It looks good!

`getClassDef(BSnew)`
An object of type 'BSseq' with
  46594397 methylation loci
  48 samples
has not been smoothed
All assays are in-memory

thanks a lot!
